version: '2'
services:
    platform-ms:
      container_name: platform-ms
      build:
        context: .
        dockerfile: gateway/Dockerfile
      image: gateway/platform-ms
      restart: always
      environment:
        PRODUCTS-MS-URL: products-ms:8083/productsms
        ORDERS-MS-URL: order-ms:8082/ordersms
      depends_on:
        - products-ms
        - orders-ms
      ports:
        - 8081:8081
      networks:
        - platform-ms-cloud-network
        - products-ms-cloud-network
        - orders-ms-cloud-network
    products-ms:
      container_name: products-ms
      build:
        context: .
        dockerfile: productsms/Dockerfile
      image: ugromart/products-ms
      ports:
        - 8083:8083
      networks:
        - products-ms-cloud-network
    orders-ms:
      container_name: orders-ms
      build:
        context: .
        dockerfile: ordersms/Dockerfile
      image: ugromart/orders-ms
      ports:
        - 8082:8082
      networks:
        - orders-ms-cloud-network
networks:
  platform-ms-cloud-network:
    driver: bridge
  orders-ms-cloud-network:
    driver: bridge
  products-ms-cloud-network:
    driver: bridge
